[k3s_server]
node-01 ansible_host=127.0.0.1 ansible_connection=local

[k3s_agents]
node-02 ansible_host=10.128.15.233
node-03 ansible_host=10.128.15.238

[k3s_cluster:children]
k3s_server
k3s_agents

[k3s_agents:vars]
ansible_user=suporte
ansible_ssh_private_key_file=/home/suporte/.ssh/chave.pem
