grafana:
  enabled: true
  adminPassword: admin123
  service:
    type: NodePort
    nodePort: 30300

prometheus:
  service:
    type: NodePort
    nodePort: 30090

  prometheusSpec:
    retention: 2d
    retentionSize: 2GB
    resources:
      requests:
        cpu: 200m
        memory: 512Mi
      limits:
        cpu: 800m
        memory: 1Gi

    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false

alertmanager:
  enabled: true
  service:
    type: NodePort
    nodePort: 30093

prometheus-node-exporter:
  enabled: true

kube-state-metrics:
  enabled: true
